//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TASON.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TASON.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITASONListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TASONBaseListener : ITASONListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TASONParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] TASONParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TASONParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] TASONParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectValue([NotNull] TASONParser.ObjectValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectValue([NotNull] TASONParser.ObjectValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayValue([NotNull] TASONParser.ArrayValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayValue([NotNull] TASONParser.ArrayValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringValue([NotNull] TASONParser.StringValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringValue([NotNull] TASONParser.StringValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberValue([NotNull] TASONParser.NumberValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberValue([NotNull] TASONParser.NumberValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BooleanValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanValue([NotNull] TASONParser.BooleanValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BooleanValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanValue([NotNull] TASONParser.BooleanValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NullValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullValue([NotNull] TASONParser.NullValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NullValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullValue([NotNull] TASONParser.NullValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>TypeInstanceValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeInstanceValue([NotNull] TASONParser.TypeInstanceValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>TypeInstanceValue</c>
	/// labeled alternative in <see cref="TASONParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeInstanceValue([NotNull] TASONParser.TypeInstanceValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TASONParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] TASONParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TASONParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] TASONParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ScalarTypeInstance</c>
	/// labeled alternative in <see cref="TASONParser.typeInstance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalarTypeInstance([NotNull] TASONParser.ScalarTypeInstanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ScalarTypeInstance</c>
	/// labeled alternative in <see cref="TASONParser.typeInstance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalarTypeInstance([NotNull] TASONParser.ScalarTypeInstanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectTypeInstance</c>
	/// labeled alternative in <see cref="TASONParser.typeInstance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectTypeInstance([NotNull] TASONParser.ObjectTypeInstanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectTypeInstance</c>
	/// labeled alternative in <see cref="TASONParser.typeInstance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectTypeInstance([NotNull] TASONParser.ObjectTypeInstanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TASONParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] TASONParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TASONParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] TASONParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TASONParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] TASONParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TASONParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] TASONParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringKey</c>
	/// labeled alternative in <see cref="TASONParser.key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringKey([NotNull] TASONParser.StringKeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringKey</c>
	/// labeled alternative in <see cref="TASONParser.key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringKey([NotNull] TASONParser.StringKeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="TASONParser.key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] TASONParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="TASONParser.key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] TASONParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TASONParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] TASONParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TASONParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] TASONParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TASONParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] TASONParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TASONParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] TASONParser.NumberContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace TASON.Grammar
